title: 'Sally Laboratory'
description: 'your web description'
keywords: 'your web keywords, another keywords'
url: 'https://sally4388you.github.io'

nav:
  Home: '/'
  Blogs: '/tags.html'
  # Timeline: '/timeline.html'
  Project Showcase: '/friendLink.html'
  About: '/about.html'

author: true
name: 'Sally Qi'
NickName: 'Sally'
webtitle: 'Sally Lab'
bio: 'ty'
about: true
aboutyou: 'your introduction'
portraits: '/assets/profile.jpeg'

SNS: true
SNS-icon:
  mail: 'mailto:sally.qibuer@gmail.com'
  weixin: 'sally4388you'
  qq: '438824887'
  github: ''
  Facebook: ''

paginate: 2
paginatepath: ['page:num']

footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
# options: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 
pygmentsTheme: 'friendly'

friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
